name: picturejeff
favicon: null
layout_spectrum: 0.9697205112315714
typography_spectrum: 0.03810929995961487
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b5daf0'
    - '#1072b5'
    - '#58443a'
    - '#52a5d8'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
